### ISSUE TITLE
Deprecated package dependencies (inflight, rimraf, glob)

### ISSUE THREAD

**Issue by ghost** [sapics/geoip-country#29]
Many millions of users around the world started experiencing some warnings that their packages are deprecated. I had an issue with the following three packages:

- inflight@1.0.6
- glob@7.2.3
- rimraf@2.7.1

By running `npm ls inflight`, it lead me to `geoip-country` (using all three of those packages).

```
geoip-country@4.2.101
  └─┬ rimraf@2.7.1
    └─┬ glob@7.2.3
      └── inflight@1.0.6
```

In other words, **rimraf@2.7.1**. is the culprit in this.

I think it's a good idea we go over the package dependencies in this project and ensure we get rid of the deprecated ones. Is anyone already working on this?

**Comment by trim21** [comment]
I'm gueesing this is because maintainers still want to support node 0.10

https://github.com/sapics/geoip-country/blob/e5dac0e52ffda3eb73cdd33111ee02209bf169ae/.github/workflows/test.yml#L12

https://github.com/sapics/geoip-country/blob/e5dac0e52ffda3eb73cdd33111ee02209bf169ae/package.json#L30-L32

but even nodejs 14 has reach its end-of-life for 2 years.

**Comment by sapics** [comment]
Sorry for late response.

As @trim21 said, I want to use the package in older node version, thus I did not update old packages.
Anyway, removing the package was just a small modification, so I have fixed.
